### ISSUE TITLE
RSS feed (combined) generation also in feed formats (RSS2/ATOM)

### ISSUE THREAD

**Issue by IoApo** [osmoscraft/osmosfeed#1]
Hi and congratulations on your effort and idea! 

I would like to ask for an idea/implementation regarding the combined list of RSS feeds. Is it possible to combine RSS feeds (the results of the generated html page maybe?) to a new "unified"-RSS-feed (in ATOM/RSS2), so that it can also be able to be used in other services (eg Feedburner, IFTTT, Ms Flow or others) or implementations? It can be optional via a set of configuration variables or something similar... (also built-in on the template page as a <link>reference if it is configured as active)

I am not sure how easy it can be, or if that is even the scope of this set of scripts, it could be nice to suggest it, for a future work maybe...

Thank you!

**Comment by chuanqisun** [comment]
Thanks! There already is [a machine readable output in json format](https://osmoscraft.github.io/osmosfeed-demo/cache.json) but that's not adhering to a standard feed format and the output is not a flat list yet. So in the short term, if you are comfortable with some json parsing, IFTTT and Ms Flow could already consume the generated output.

You can also use http://www.rssmix.com/ to achieve the same goal.

Would either option meet your requirement?

**Comment by IoApo** [comment]
Thank you for the fast reply! Sure, I would try to seek for some implementations and do some further testing! 

Congrats again and keep up the good work! 👍

**Comment by chuanqisun** [comment]
Converted to a discussion. See #12
