### ISSUE TITLE
Customizable lifespan for content cache

### ISSUE THREAD

**Issue by dwarkeshsp** [osmoscraft/osmosfeed#2]
This is really awesome!!! Do you know what code I can edit to render more than a month of previous content on my website? The oldest seem to only be about a month old. Thanks so much!

**Comment by chuanqisun** [comment]
Thanks mate! I hard coded that as the `MAX_AGE_DAYS` parameter here: https://github.com/osmoscraft/osmosfeed/blob/master/src/lib/enrich.ts#L12

I'll expose that through in the `osmosfeed.yaml` file so you can change it.

**Comment by dwarkeshsp** [comment]
Thank you so much! I'm already getting so much value from product. Feedly and other readers make it so hard to just see all the articles in this simple way. I'm glad you made this.

**Comment by chuanqisun** [comment]
@dwarkeshsp done. You can set `cacheMaxDays` in the `osmosfeed.yaml`. Documentation here: https://github.com/osmoscraft/osmosfeed/blob/master/docs/osmosfeed-yaml-reference.md

**Comment by dwarkeshsp** [comment]
Thanks so much! I'm going to share this with my friends, who will get great value from it too!
