### ISSUE TITLE
Scripts is not copying CNAME when generating gh-pages branch

### ISSUE THREAD

**Issue by ramonmedeiros** [osmoscraft/osmosfeed#22]
**Describe the bug**
Github Pages with custom domains needs CNAME

**Bug area (choose one)**
- [x] Site builder: anything broken during in the GitHub action
- [ ] Reader UI: anything broken while you are reading the feed

**To reproduce the bug**
- Share your repo https://github.com/ramonmedeiros/feed
- Share the reader UI site https://feed.ramonmedeiros.dev

**Expected behavior**
When running osmofeed, if CNAME is found, copy to gh-pages branch

**Screenshots**

**Additional context**

**Comment by chuanqisun** [comment]
@ramonmedeiros, did you close by accident or did you find a work around? I want to make sure you can bring your own host.

**Comment by chuanqisun** [comment]
@ramonmedeiros static asset copy is implemented. [Documentation](https://github.com/osmoscraft/osmosfeed/blob/master/docs/customization-guide.md)

Thank you again for making this tool better!
