### ISSUE TITLE
`description` field shouldn't be truncated when it is a properly sized synopsis.

### ISSUE THREAD

**Issue by LooperXX** [osmoscraft/osmosfeed#37]
**Describe the bug**
Like https://github.com/osmoscraft/osmosfeed/issues/6#issue-873942524, I would appreciate if there is an option, e.g. set in `osmosfeed.yaml` to display the feed description. 
Actually, in my case, the feed description is an abstract of each paper. Now it will be truncated because the maximum length doesn't big enough.

**Bug area (choose one)**
- [ ] Site builder: anything broken during in the GitHub action
- [x] Reader UI: anything broken while you are reading the feed

**To reproduce the bug**
- Share your repo (if visible to public)
    - https://looperxx.github.io/ArxivDaily/

**Expected behavior**
I can set the maximum length of the feed description in `osmosfeed.yaml`.

**Comment by chuanqisun** [comment]
Thank you for bring this to my attention. Issue acknowledged. There is some unfortunate history behind why I had to truncate:
- According to RSS spec, the `description` field is meant for synopsis, which arxiv correctly used, but websites have misused it to display full text.
- The current osmosfeed frontend uses a single static html file. If I don't truncate, there is a risk of generating extremely large index.html (e.g. 20 source * 50 item per source * 100KB per article  = 100MB).
- The current cache is atomic. If user built a huge cache by mistake, fixing it requires destroying all the cached history.
- Atom feed has a dedicated `summary` field, which is the perfect field for abstract. Sadly, the format is too hard to implement, so most sites stayed with RSS.

My current plan
- If the source is Atom, use the `summary` field and never truncate it.
- **Add a global config to customize max description length. You can set it to 9999 (this should be a quick fix to solve your problem)**
- If the source is RSS, expose a config option to set `truncation: false` (this would allow fine control over a mixture of sources that use `description` for either full text or synopsis)
  - This should only be configured per source and set to `truncation: true` by default, for the reasons above.
- Longer term, figure out a better caching system, so the frontend can fetch the full article asynchronously without bloating index.html
- Longer term, parse the full text better, so as to preserve white space between paragraphs and support rich media embed: including image and code snippets.

(p.s. nice hack to show the author and keywords!)

**Comment by LooperXX** [comment]
Thank you for your prompt and detailed response! 
I can fully understand why it was truncated. I agree with you that expose a config option to set truncation per source and set to `truncation: true` by default  for caching consideration. 
Thanks for your great work and detailed response!

**Comment by chuanqisun** [comment]
Release [v1.8.0](https://github.com/osmoscraft/osmosfeed/releases/tag/v1.8.0) should fix it.

Instead of asking user to configure each source, I relaxed the truncation threshold and decoupled the truncation threshold from the truncation size. With some Bayesian reasoning, here is the new algorithm:

```javascript
if (content.length > 2048) { /* content is likely full text */
  return content.truncateTo(800) /* There is no point going above 800. Reading full text without line break is painful */
} else { /* The `content` is likely synopsis. */
  return content; /* Size can go up to 2048. The synopsis should hold up just fine without line break */
}
```
I did a quick check of all your arxiv feed content. The abstract length range between 600 and 1600, so the 2048 char limit should be a safe limit for you.
In retrospect, `truncation: false` doesn't make much sense given there will be no line break in the middle. The design of the site was optimizing for a quick summary/abstract/synopsis. I'll track full text reading experience separately in #39.

Let me know if this helps.

**Comment by LooperXX** [comment]
@chuanqisun, Thanks for your quick response and update! The abstract in my site is now complete. This will be of great help to my work. Thanks again!

**Comment by chuanqisun** [comment]
btw @LooperXX, is it ok if I showcase your customization in the community [Show & tell](https://github.com/osmoscraft/osmosfeed/discussions/categories/show-and-tell)? I really love the keyword highlight and the author tags. I thought sharing your customization could benefit other users who use osmosfeed for academic reading.

**Comment by LooperXX** [comment]
@chuanqisun, Of course! I will recommend osmosfeed to my friends and I am willing to share my customization to help other users! If it can help osmosfeed and other users, it is my pleasure!
