### ISSUE TITLE
iTunes feed metadata is stripped

### ISSUE THREAD

**Issue by Zenigata** [osmoscraft/osmosfeed#45]
I want to retrieve other fields in the RSS XML, especially the itunes:duration. I am currently displaying a MP3 feed.
Maybe a mechanism to add any given fields would be wonderful.

**Comment by chuanqisun** [comment]
Happy to look into this. Extensible data format is on the roadmap, potentially via **data plugins** (see #31). Would you might providing a bit more context? Maybe I can come up with a quick & easy solution:

1. Could you share one or two examples of mp3 based RSS source?
2. How do you plan to use those additional fields?
    1. If you plan to display info on the web frontend, what fields are the most important to you?
    2. What if those additional fields are only available in the machine readable output (instead of in the web frontend)?

**Comment by Zenigata** [comment]
Thanks for your quick response! I have set up this one yesterday: https://zenigata.github.io/les-dernieres-fictions-sonores/
Instead of readingTimeInMin, I'd have a listeningTimeInMin field, whose source could be <itunes:duration> like in https://www.linaudible.com/feed/podcast/ or https://feed.ausha.co/Zb30tRPGX70B.

For now, I only plan to use this one instead of the readingTimeInMin as shown on the template's button.
Another interesting field would be the cover (an image provided by the feed on each article). I know some like to keep it minimalistic, but I could enjoy a cover picture.

If the field is already available in the machine output, one could already transform it for display in index.hbs. I'd start with that.

**Comment by chuanqisun** [comment]
Thank you for adding the details. Expect an experimental support of iTunes feed in the next minor release.

**Comment by chuanqisun** [comment]
@Zenigata, see release [v1.9.0](https://github.com/osmoscraft/osmosfeed/releases/tag/v1.9.0) 
Let me know how this works (or doesn't work) for you. Happy to provide some additional help on if templating becomes cumbersome. I'll address some of the caveats mentioned in the release notes in future releases.

**Comment by Zenigata** [comment]
I'm so glad you added it so quickly! Unfortunately it doesn't work for me. I'll try to find why quickly.
