### ISSUE TITLE
Allow users to change the theme

### ISSUE THREAD

**Issue by benthecoder** [osmoscraft/osmosfeed#5]
Really love this! Can't wait to see more development and features! I'm sorry if this is a bad question, but is there a way to choose templates/themes for the rss reader? Or is this theme the only one that's available now?

**Comment by benthecoder** [comment]
Another question I have is whether the rss feeds can be centered because I use a big monitor and all the feeds are at the left which isn't a nice viewing experience. I would rather have everything at the center. Is this possible? Thank you.

**Comment by spitlo** [comment]
If there was a way to include your own stylesheet, that would be great! Either by supplying a path to a custom stylesheet in `osmosfeed.yaml`, or by simply placing a `styles.css` file in the root.

**Comment by chuanqisun** [comment]
Thank you for bringing this up @benthecoder and thank you @spitlo for the idea. I definitely plan to support theming and that will be a core feature of this tool. The current theme ([gruvbox](https://github.com/morhetz/gruvbox)) is implemented with the [base16 architecture](https://github.com/chriskempson/base16) so swapping shouldn't be hard.

Please note, this project suddenly received way more attention than I expected, so please give me some time to get the technical design and implementation right for this very important feature. I want to keep the system modular so the basic experience is always simple and lightweight, but for advanced users, they will have full control, either through osmosfeed.yaml, or extensions/plugins via npm.

Thank you again. I'll create a separate issue to track the work.
