### ISSUE TITLE
URL中出现中文会报错

### ISSUE THREAD

**Issue by CaptNo1** [osmoscraft/osmosfeed#59]
RSS链接中出现中文会出现"ERR_UNESCAPED_CHARACTERS"错误，应该是编码问题

**Comment by chuanqisun** [comment]
Thanks for the repo @CaptNo1 !

I have fixed the issue in #60 . You just need to rebuild your feed (with v1.11.2 release)

Now this setup in `osmosfeed.yml` should work:
```yml
sources:
  - href: https://rsshub.lucian.site/weibo/user/5675300793?filter=非人哉..【第[1-9]\d*话】 
```

![image](https://user-images.githubusercontent.com/1895289/134820444-b611bb21-1761-47c2-9d89-f842fe5eb35d.png)
