### ISSUE TITLE
Option to not shorten the feed articles

### ISSUE THREAD

**Issue by luben** [osmoscraft/osmosfeed#6]
I would appreciate if there is an option, e.g. set in `osmosfeed.yaml` to display unmodified `content:encoded` if available (from the RSS feed itself). I am not sure if it's related but I will also appreciate showing the images, e.g. XKCD strips from https://xkcd.com/rss.xml, inline.

**Comment by chuanqisun** [comment]
Thanks for the feedback @luben. I've been considering extracting a "cover image" from the article content. Would that address your core issue? Or there is something else in the unmodified encoded content you'd need?

**Comment by luben** [comment]
Yes, that's one option. Also I noticed my first request didn't make a lot of sense (opposite of the title), so I edited it.

**Comment by 2m** [comment]
I would also love such feature. Browsing through my oldest RSS feeds, I see that some of the articles are no longer accessible. Having osmofeed store the content of the article would be perfect for archiving purposes.

**Comment by chuanqisun** [comment]
@2m , thank you for providing the motivation. I have converted your ask to #14.
