### ISSUE TITLE
README url error

### ISSUE THREAD

**Issue by tianheg** [osmoscraft/osmosfeed#65]
**Describe the bug**
404 url

**Bug area (choose one)**
[here](https://github.com/osmoscraft/osmosfeed/blob/master/README.md#can-i-make-the-site-private-so-only-i-can-see-it)

> For example, if you deploy to Netlify,

**Comment by chuanqisun** [comment]
I fixed the [link](https://github.com/osmoscraft/osmosfeed/blob/master/docs/how-to-deploy-to-other-hosts.md). And if you need any additional help deploying to Netlify, just reopen the issue.

谢谢!
