### ISSUE TITLE
Cannot download RSS caused by "Limit reached for max number of failed attempts"

### ISSUE THREAD

**Issue by chuanqisun** [osmoscraft/osmosfeed#69]
### Discussed in https://github.com/osmoscraft/osmosfeed/discussions/67

<div type='discussions-op-text'>

<sup>Originally posted by **sokomin** December 12, 2021</sup>
I'm using osmosfeed RSS, but it sometimes occur the following error.

```
[download] 0 attempts left, error download ...
      throw new Error(`[download] Limit reached for max number of failed attempts`);
            ^

Error: [download] Limit reached for max number of failed attempts
    at downloadHelper (/home/runner/work/RS-RSS/RS-RSS/node_modules/@osmoscraft/osmosfeed/bin/main.js:31974:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async enrichInternal (/home/runner/work/RS-RSS/RS-RSS/node_modules/@osmoscraft/osmosfeed/bin/main.js:32023:21)
    at async Promise.all (index 6)
    at async run (/home/runner/work/RS-RSS/RS-RSS/node_modules/@osmoscraft/osmosfeed/bin/main.js:32229:27)
Error: Process completed with exit code 1.
```

we can access the RSS link, but the program can't recognize the rss feed.
Some website is OK, but a few site was not accessed.

Can you help me?
When some RSS acquisition stops, the whole build will stop.
If you don't know the cause of the error, I would like to resolve it so that I can get the RSS partially.

Here is the project.
https://github.com/sokomin/RS-RSS/actions

Thanks,</div>

**Comment by chuanqisun** [comment]
Plan is to either
1. Relax timeout and retry,
2. OR allow partial success build to publish

The second option must be carefully designed so that it does not wipe out previously successful builds.

**Comment by chuanqisun** [comment]
@sokomin, I've implemented error boundary and recovery, so the download error from one source will not crash the build. In addition, cached data will be used as fallback.


The fix is released in v1.13.0

Your latest run shows successful recovery from several download errors: https://github.com/sokomin/RS-RSS/runs/4757288148?check_suite_focus=true

(By the way, your home page is beautifully designed, can you take a screenshot and make it into a showcase?)

In the meanwhile, I've checked the root cause of the errors, I think the reason is complex:

1. Some services give 503 error code. In this case, the server is busy. There is nothing we can do.
2. Some services timed-out. I've looked at the timeout logic. We have 3 retires: 10 seconds -> 15 seconds -> 22.5 seconds. In my opinion, 22.5 seconds is very generous timeout. I've also tested locally (I'm in the US) with 5 retries and 20 second -> 30 -> 45 timeout, still getting the same errors. My concern with more retires and longer timeout is that your Github Action will run of out monthly quota. However, if you still believe longer timeout and more retries will help, just let me know. I can add options in the config.
3. Most of your servers appear to be in Japan. GitHub action agents are probably located the West US. This means connection will be generally unstable. GitHub doesn't let us choose location right now

**Comment by sokomin** [comment]
@chuanqisun Thank you very much!
After the update, the build error no longer occurs.
A detailed explanation of the timeout issue is also helpful.

> (By the way, your home page is beautifully designed, can you take a screenshot and make it into a showcase?)

Thank you for your love, no ploblem!
Here is a screenshot.
![スクリーンショット 2022-01-12 043318](https://user-images.githubusercontent.com/2122504/149009208-1012c56b-c6a4-485d-9ed3-a3f754da3ba0.png)

**Comment by chuanqisun** [comment]
I created #74 to showcase your work! Thank you again. Just let me know if you need any help in the future.
