### ISSUE TITLE
Expand/Collapse details for all articles

### ISSUE THREAD

**Issue by luben** [osmoscraft/osmosfeed#7]
It would be great if there are buttons to expand/collapse all articles. Also if there is a setting to change the default to "expanded" it would be great.

**Comment by chuanqisun** [comment]
Hi @luben, thanks again for providing all the feedback to this tool. I have a couple of technical designs in mind:

1. Provide unobtrusive keyboard shortcut to expand/collapse all, with no UI buttons.
2. Render all the articles without using the `<details><summary>` elements. There will be a flat list on the home page.
3. Allowing a custom html renderer so you can provide any HTML you want. The tool will provider data in a standard interface.

Ultimately I want to support No.3 as it enables infinite customizability, but in the short term, how might No.1 and 2 relate to your goal?

**Comment by luben** [comment]
Yes, flat list or shortcut will solve the problem.
