### ISSUE TITLE
If link tag is relative, host is not prepended

### ISSUE THREAD

**Issue by cpwnd** [osmoscraft/osmosfeed#82]
**Describe the bug**
*I'm not sure if its a feature or a bug.*

If the value inside the link tag is relative like `/posts/index.html` then the url host is not prepended to form a valid url to request it.
I've seen pythons `feedparser` lib behave this way.
I don't know if that's very common for an rss reader lib.
At least the standard does not contain rules for handling relative links.
https://validator.w3.org/feed/docs/rss2.html

So I assume it would be a feature then, but I will let decide you. 

**Bug area (choose one)**
- [ ] Site builder: anything broken during in the GitHub action
- [x] Reader UI: anything broken while you are reading the feed

**To reproduce the bug**
Try to download this rss feed url:
`https://www.osnabrueck.de/start?type=9818`

**Expected behavior**
I expected from experience with other rss libs before, that osmosfeed also prepends the host from the url to the relative url inside the link tag.

**Comment by chuanqisun** [comment]
Thanks for the investigation! The spec isn't very specific about how to handle relative URLs. Ideally, a source should use `xml:base` to indicate the base of the relative URL, but when that is missing, there is some unofficial recommendation to infer that from the channel link:

>  We are inclined to recommend that all RSS readers honor xml:base when present. We are inclined to recommend that RSS readers construe /rss/channel/link as the base by default, and xml:base (if present) as an override (if the base must differ from /rss/channel/link).
> Source: https://cyber.harvard.edu/rss/relativeURI.html

In my opinion, it is reasonable for RSS readers to normalize non-standard content if
1. The normalization does not change or invalidate any existing content within the standard, AND
2. The normalization does not prevent the standard evolves in the future.

For 1), Resolving relative URLs will not impact the handling of absolute URLs 
For 2), If the standard makes `xml:base` official, or requires base inferring, there will be no breaking change.

By this logic, I think inferring base URL should be safe, but please call out if people disagree.

I'll implement in the next release.

**Comment by chuanqisun** [comment]
Fixed in #83, available in release [v1.15.0](https://github.com/osmoscraft/osmosfeed/releases/tag/v1.15.0). Thank you @cpwnd!

![relative-url-resolution](https://user-images.githubusercontent.com/1895289/174452858-4b4b9e7c-f416-475a-b42a-af6a61319e4d.png)
